# Use official Python 3.12 image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire app folder (including templates and static folders)
COPY . .

# Expose the Flask port
EXPOSE 5003

# Run the Flask app
#CMD ["python3", "app.py"]
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "-p 5003"]
